---
title: "ADAM DZ"
author: "Irina Garanina"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)
library(expss)
```

```{r pressure, echo=FALSE}
mh <- read.xlsx("ADaM coding/SDTM/MH_MEDICALHISTORY.xlsx")
adsl <- read.xlsx("ADaM coding/ADaM-like/ADSL.xlsx")
```

```{r}
ADMH <- left_join(mh, adsl) %>%
  mutate_all(~na_if(.,"")) %>%
  filter(!is.na(MHTERM) & MHCAT == "Medical History") %>% 
  #согласно ADAM IG разделу 4.4, если включение записей, ненужных для анализа не практично, то их разрешается не включать
  mutate(
    STUDYID = as.character(STUDYID),
    USUBJID = as.character(USUBJID),
    TRTP = as.character(TRTP),
    TRTPN = as.integer(TRTPN),
    MHSEQ = as.integer(MHSEQ),
    MHCAT = ifelse(MHCAT == "Medical History", MHCAT, NA),
    MHTERM = as.character(MHTERM),
    MHDECOD = as.character(MHDECOD),
    MHBODSYS = as.character(MHBODSYS),
    MHSTDTC = as.character(MHSTDTC),
    
    #обработка дат
    ASTDT = case_when(
    is.na(MHSTDTC) ~ NA_character_,
    #полная дата
    grepl("^\\d{4}-\\d{2}-\\d{2}$", str_trim(MHSTDTC)) ~ format(as.Date(MHSTDTC, 
                                  format = "%Y-%m-%d"), "%d.%m.%Y"), 
    #только месяц и год
    grepl("^\\d{4}-\\d{2}$", str_trim(MHSTDTC)) ~ format(as.Date(paste0(MHSTDTC, "-01"),format = "%Y-%m-%d"), "%d.%m.%Y"),  
    #только год
    grepl("^\\d{4}$", str_trim(MHSTDTC)) ~ format(as.Date( paste0(MHSTDTC, "-01-01"         ),format = "%Y-%m-%d"), "%d.%m.%Y"),  
    TRUE ~ paste("Неверный формат даты начала:", MHSTDTC)
    ),
    
    ASTDTF = case_when(
    is.na(MHSTDTC) ~ "Y",  #нет даты
    nchar(MHSTDTC) == 7 ~ "D",  #только месяц и год
    nchar(MHSTDTC) == 4 ~ "M",  #только год
    TRUE ~ NA_character_ 
    ),
    MHENDTC = as.character(MHENDTC),
    AENDT = case_when(
    MHENRTPT == "ONGOING" ~ "", 
    #полная дата
    grepl("^\\d{4}-\\d{2}-\\d{2}$", str_trim(MHENDTC)) == 10 ~ format(as.Date(MHENDTC, format = "%Y-%m-%d"), "%d.%m.%Y"),
    #только месяц и год
    grepl("^\\d{4}-\\d{2}$", str_trim(MHENDTC)) ~ format(as.Date(paste0(MHENDTC, "-01"),format = "%Y-%m-%d"), "%d.%m.%Y"),  
    #только год
    grepl("^\\d{4}$", str_trim(MHENDTC)) ~ format(as.Date(paste0(MHENDTC, "-01-01"         ),format = "%Y-%m-%d"), "%d.%m.%Y"),  
    TRUE ~ paste("Неверный формат даты конца:", MHENDTC)
    ),
    
    AENDTF = case_when(
    is.na(MHENDTC) ~ "Y",  #нет даты
    nchar(MHENDTC) == 7 ~ "D",  #только месяц и год
    nchar(MHENDTC) == 4 ~ "M",  #только год
    TRUE ~ NA_character_
    ),

    MHENRTPT = as.character(MHENRTPT),
    MHENRF = ifelse(MHENRTPT == "ONGOING", "ONGOING", "")
    ) %>% 
apply_labels(
    STUDYID="Study Identifier",
    USUBJID="Unique Subject Identifier",
    TRTP="Planned Treatment",
    TRTPN="Planned Treatment (N)",
    MHSEQ="Sequence Number",
    MHCAT="Category for Medical History",
    MHTERM="Reported Term for the Medical History",
    MHDECOD="Dictionary-Derived Term (PT)",
    MHBODSYS="Body System or Organ Class (SOC)",
    MHSTDTC="Start Date/Time of Medication",
    ASTDT="Analysis Start Date",
    ASTDTF="Analysis Start Date Imputation Flag",
    MHENDTC="End Date/Time of Medication",
    AENDT="Analysis End Date",
    AENDTF="Analysis End Date Imputation Flag",
    MHENRTPT="End Relative to Reference Time Point",
    MHENRF="Continuation Flag"
) %>%
   select(
    STUDYID, USUBJID, TRTP, TRTPN, MHSEQ, MHCAT, MHTERM, MHDECOD, MHBODSYS,
    MHSTDTC, ASTDT, ASTDTF, MHENDTC, AENDT, AENDTF, MHENRTPT, MHENRF
  ) %>%
  arrange(STUDYID, USUBJID, MHSEQ)
```

```{r}
write.xlsx(ADMH, "ADaM coding/ADaM-like/ADMH.xlsx")
```
