---
title: "R Notebook Basisc of Data Visualization with R"
author: "Irina Garanina"
date: 16.09.2024
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE, fig.width=16, fig.height=10)
library('readr')
library('tibble')
library('dplyr')
library('stringr')
library('tidyr')
library('stringi')
library('flextable')
library('ggplot2')
library(forcats)
theme_custom = theme(axis.title = element_text(size = 25),  axis.text = element_text(size = 20), legend.title = element_text(size = 25),  legend.text = element_text(size = 20), plot.title = element_text(hjust = 0.5, size = 25) ,plot.subtitle = element_text(hjust = 0.5, size = 20) )
```

```{r}
## Data reading

hogwarts <- read_csv("dayavis_BI_2024/data/hogwarts_2024.csv")
hogwarts |> head()
```

```{r}
hogwarts |> glimpse()
```

```{r}
#preparing data
hogwarts <- hogwarts |> mutate(
  across(c(house, course, sex, wandCore, bloodStatus), ~ as.factor(.x))
)
```

```{r}
#bars task 1
ggplot(data = hogwarts, aes(x = course)) + 
  geom_bar(colour = 'red', fill = '#019834') + 
  theme_bw() +
  theme_custom

```

```{r }
#bars task 2, conclusion that both Gryffindor and Slytherin has highest percentage #of pure-blood students, but Gfyffindor has more than twice higher percentage of #muggle-borns compared with Slytherin, and the highest among all houses

ggplot(data = hogwarts) + 
  geom_bar(aes(x = house, fill = bloodStatus), position = "fill") + 
  theme_light() +
  theme_custom

```

```{r}
#bars task 3
hogwarts |> filter(bloodStatus %in% c('pure-blood', 'muggle-born')) |> 
ggplot() + 
  geom_bar(aes(x = house, fill = bloodStatus), position = "fill") + 
  theme_light() +
  theme_custom +
  geom_hline(yintercept = 0.5, colour = 'blue3') + 
  labs(x = "Факультет", y = "Доля",  fill = "Происхождение") +
  scale_fill_manual(
    values = c("pure-blood" = "red3", "muggle-born" = "green3"),
    labels = c("pure-blood" = "Чистокровный", "muggle-born" = "Маглорожденный")
  )
  
```

```{r, fig.width=14, fig.height=14}
#boxplots tasks 1-3
ggplot(hogwarts, aes(x = fct_reorder(house,week_3, .desc = TRUE) , y = week_3, fill = bloodStatus))+
  geom_boxplot(notch = TRUE, outliers = FALSE, width = 0.5, size = 0.5)+
  geom_jitter(width = 0.25) +
  theme_bw()+
  theme_custom +
  labs(x = "Факультет", y = "Оценки в неделю 3",  fill = "Происхождение") +
  scale_fill_manual(
    values = c("pure-blood"="red3", "muggle-born"='yellow3', "half-blood"='green3'), 
    labels = c("pure-blood" = "Чистокровный", "muggle-born" = "Маглорожденный", "half-blood" = "Полукровка")
  ) +
  ggtitle("Оценки в неделю 3 по факультетам", "Факультеты отсортированы в порядке убывания медианной оценки")

```

```{r, fig.width=14, fig.height=25}
#other task 1
hogwarts |> 
  filter(course == 5 ) |> mutate(id = as.factor(id)) |>
  mutate(overal_mark = rowSums(across(contains("week")))) |>
  ggplot() +
  geom_segment(aes(y = fct_reorder(id, overal_mark), 
                   yend = fct_reorder(id, overal_mark), 
                   x = 0, 
                   xend = overal_mark)) + 
  theme_bw()+
  theme_custom +
  scale_x_continuous(breaks = seq(-225, 225, by = 50)) +
  geom_vline(xintercept = 0) +
  labs(x = "Итоговый балл", y = "ID студента", color = "Сердцевина палочки") +
  geom_point(aes(y = fct_reorder(id, overal_mark), 
                 x = overal_mark, colour = wandCore), 
             size = 3) +
  scale_color_manual(
    values = c("dragon heartstring"="red3", "phoenix feather"='yellow2', "unicorn hair"='grey'),
    labels = c("dragon heartstring" = "Сердце дракона", "phoenix feather" = "Перо феникса", "unicorn hair" = "Волос единорога"))
  
  
```

```{r}
#other task 2
ggplot(data = hogwarts, aes(x = `Astronomy exam`, fill = house == "Slytherin")) + 
  geom_histogram(binwidth = 5, colour = 'red') + 
  scale_fill_manual(values = c("TRUE" = "green", "FALSE" = "grey")) +  
  labs(fill = "Slytherin", y = 'Number of students') +
  theme_bw() +
  theme(axis.text = element_text(size = 18),legend.text = element_text(size = 18), axis.title.x = element_text(size = 22), legend.title = element_text(size = 20), axis.title.y = element_text(size = 20))

```

```{r}
#other task 3
theme_custom_bg = theme(#старые настройки
                        axis.title = element_text(size = 25),
                        axis.text = element_text(size = 20),
                        legend.title = element_text(size = 25),
                        legend.text = element_text(size = 20),
                        plot.title = element_text(hjust = 0.5, size = 25),
                        plot.subtitle = element_text(hjust = 0.5, size = 20),
                        #белый фон 
                        panel.background = element_rect(fill = "white", color = NA),
                        #рамка
                        panel.border = element_rect(color = "black", fill = NA, size = 0.5),
                        #сетка
                        panel.grid.major = element_line(color = "lightgray", size = 0.5))

ggplot(hogwarts, aes(x = fct_reorder(house,week_3, .desc = TRUE) , y = week_3, fill = bloodStatus))+
  geom_boxplot(notch = TRUE, outliers = FALSE, width = 0.5, size = 0.5)+
  geom_jitter(width = 0.25) +
  theme_custom_bg +
  labs(x = "Факультет", y = "Оценки в неделю 3",  fill = "Происхождение") +
  scale_fill_manual(
    values = c("pure-blood"="red3", "muggle-born"='yellow3', "half-blood"='green3'), 
    labels = c("pure-blood" = "Чистокровный", "muggle-born" = "Маглорожденный", "half-blood" = "Полукровка")
  ) +
  ggtitle("Оценки в неделю 3 по факультетам", "Факультеты отсортированы в порядке убывания медианной оценки")

```

```{r}
#facets task 1
#Для гистрограмм когда они находятся друг пож другом как в самомпервом примере фасетирования, тк удобнее сравнивать #гистограммы мне у них медианы, хвосты и пр. ДЛя violin plot наоборот тк медианы варьируют в вертикальном #направлении в зависимости от данных. Общее правило такое, что если основная метрика, на которую смотрим варьирует #по вертикали, тогда графики удобнее сравнивать в одном ряду, а если по горизонтали, то друг под другом.
```

```{r}
#facets task 2
ggplot(data = hogwarts, aes(x = `Astronomy exam`)) + 
  geom_histogram(binwidth = 5, colour = 'red') + 
  labs(y = 'Number of students') +
  theme_bw() +
  theme_custom + facet_wrap(vars(course))
```

```{r}
#facets task 3
hogwarts |> pivot_longer(cols = c(`Defence against the dark arts exam`, `Herbology exam`), names_to = "Subject", values_to = "Score") |> 
ggplot() + 
  geom_density(aes(x = Score, fill = Subject), alpha = 0.5) +
  scale_fill_manual(
    values = c("Defence against the dark arts exam" = "black", "Herbology exam" = "green"),
    name = "Subject",
    labels = c("Defence against the dark arts exam", "Herbology exam")) + 
  theme_custom_bg + facet_grid(sex~.) + 
  labs(x = 'Student score')
```
